### PR TITLE
Fix farious errors and warnings

### PR DESCRIPTION
**Pull request by awulkiew**
Fix compilation errors introduced by https://github.com/boostorg/geometry/pull/1014
Fix error in area: https://github.com/boostorg/geometry/issues/1033
Fix warning in rtree: https://github.com/boostorg/geometry/issues/1032

### CODE REVIEW

**Review by vissarion — APPROVED** [review]
Thanks!

**Review by barendgehrels — APPROVED** [review]
thank you!
